version: 2  
orbs:
  test-orb: njm3754/hello-world-orb-15@dev:first
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          #Add command name and bash commands to execute
          name: Enter command description
          command: echo "Add command here"
      - test-orb/greet