version: 2  
orbs:
  test: njm3754/hello-world-orb-15@dev:first
  test-1: njm3754/test-hello-orb@1.1.2

workflows:
  version: 2

  test:
    jobs:
      - build
      - test-1/hello
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          #Add command name and bash commands to execute
          name: Enter command description
          command: echo "Add command here"
